// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Enum.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Enum.proto</summary>
public static partial class EnumReflection {

  #region Descriptor
  /// <summary>File descriptor for Enum.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static EnumReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgpFbnVtLnByb3RvKroNCghQUk9UT0NPTBIWChJJRF9QS1RfVkVSU0lPTl9S",
          "RVEQABIWChJJRF9QS1RfVkVSU0lPTl9SRVMQARIUChBJRF9QS1RfTE9HSU5f",
          "UkVREAISFAoQSURfUEtUX0xPR0lOX1JFUxADEhoKFklEX1BLVF9DUkVBVEVf",
          "Uk9PTV9SRVEQBBIaChZJRF9QS1RfQ1JFQVRFX1JPT01fUkVTEAUSGQoVSURf",
          "UEtUX0VOVEVSX1JPT01fUkVREAYSGQoVSURfUEtUX0VOVEVSX1JPT01fUkVT",
          "EAcSGQoVSURfUEtUX0xFQVZFX1JPT01fUkVREAgSGQoVSURfUEtUX0xFQVZF",
          "X1JPT01fUkVTEAkSHQoZSURfUEtUX0JJVE1BUF9NRVNTQUdFX1JFURAKEh0K",
          "GUlEX1BLVF9CSVRNQVBfTUVTU0FHRV9SRVMQCxIfChtJRF9QS1RfTkVXX1VT",
          "RVJfSU5fUk9PTV9OVFkQDBIYChRJRF9QS1RfUk9PTV9MSVNUX1JFURANEhgK",
          "FElEX1BLVF9ST09NX0xJU1RfUkVTEA4SGQoVSURfUEtUX0dBTUVfU1RBUlRf",
          "TlRZEA8SGgoWSURfUEtUX0dBTUVfUkVTVUxUX05UWRAQEiAKHElEX1BLVF9S",
          "T09NX1BBU1NfVEhST1VHSF9SRVEQERIgChxJRF9QS1RfUk9PTV9QQVNTX1RI",
          "Uk9VR0hfUkVTEBISFQoRSURfUEtUX05PVElDRV9SRVEQExIVChFJRF9QS1Rf",
          "Tk9USUNFX1JFUxAUEhwKGElEX1BLVF9BVURJT19NRVNTQUdFX1JFURAVEhwK",
          "GElEX1BLVF9BVURJT19NRVNTQUdFX1JFUxAWEhsKF0lEX1BLVF9QUkFZX01F",
          "U1NBR0VfUkVREBcSGwoXSURfUEtUX1BSQVlfTUVTU0FHRV9SRVMQGBIfChtJ",
          "RF9QS1RfUFJBWV9NRVNTQUdFX1JFR19SRVEQGRIfChtJRF9QS1RfUFJBWV9N",
          "RVNTQUdFX1JFR19SRVMQGhISCg5JRF9QS1RfUU5BX1JFURAbEhIKDklEX1BL",
          "VF9RTkFfUkVTEBwSGAoUSURfUEtUX01BSUxfTElTVF9SRVEQHRIYChRJRF9Q",
          "S1RfTUFJTF9MSVNUX1JFUxAeEhgKFElEX1BLVF9NQUlMX1NFTkRfUkVREB8S",
          "GAoUSURfUEtUX01BSUxfU0VORF9SRVMQIBIXChNJRF9QS1RfTUFJTF9ERUxf",
          "UkVRECESFwoTSURfUEtUX01BSUxfREVMX1JFUxAiEhgKFElEX1BLVF9NQUlM",
          "X1JFQURfUkVRECMSGAoUSURfUEtUX01BSUxfUkVBRF9SRVMQJBISCg5JRF9Q",
          "S1RfUkVHX1JFURAlEhIKDklEX1BLVF9SRUdfUkVTECYSHAoYSURfUEtUX0NM",
          "SUVOVF9MT0dPVVRfUkVRECcSHAoYSURfUEtUX0NMSUVOVF9MT0dPVVRfUkVT",
          "ECgSFgoSSURfUEtUX0NMSUVOVF9LSUNLECkSHQoZSURfUEtUX0NBTUVSQV9D",
          "T05UUk9MX1JFURAqEh0KGUlEX1BLVF9DQU1FUkFfQ09OVFJPTF9SRVMQKxIe",
          "ChpJRF9QS1RfTVBFRzJUU19NRVNTQUdFX1JFURAsEh4KGklEX1BLVF9NUEVH",
          "MlRTX01FU1NBR0VfUkVTEC0SHQoZSURfUEtUX0NBTUVSQV9XQUtFX1VQX1JF",
          "URAuEh0KGUlEX1BLVF9DQU1FUkFfV0FLRV9VUF9SRVMQLxIaChZJRF9QS1Rf",
          "U1RPUF9TVFJFQU1fUkVREDASGgoWSURfUEtUX1NUT1BfU1RSRUFNX1JFUxAx",
          "EhkKFUlEX1BLVF9SRUdfQ0FNRVJBX1JFURAyEhkKFUlEX1BLVF9SRUdfQ0FN",
          "RVJBX1JFUxAzEhoKFklEX1BLVF9DQU1FUkFfTElTVF9SRVEQNBIaChZJRF9Q",
          "S1RfQ0FNRVJBX0xJU1RfUkVTEDUSHQoZSURfUEtUX01BQ0hJTkVfU1RBVFVT",
          "X1JFURA2Eh0KGUlEX1BLVF9NQUNISU5FX1NUQVRVU19SRVMQNxIeChpJRF9Q",
          "S1RfVkVSSUZZX1BVUkNIQVNFX1JFURA4Eh4KGklEX1BLVF9WRVJJRllfUFVS",
          "Q0hBU0VfUkVTEDkSGQoVSURfUEtUX0RFTF9DQU1FUkFfUkVREDoSGQoVSURf",
          "UEtUX0RFTF9DQU1FUkFfUkVTEDsSGAoUSURfUEtUX1JFQ09OTkVDVF9SRVEQ",
          "PBIYChRJRF9QS1RfUkVDT05ORUNUX1JFUxA9KnsKCUVycm9yQ29kZRILCgdT",
          "dWNjZXNzEAASEQoNRGF0YUJhc2VFcnJvchABEhIKDkxvZ2luRHVwbGljYXRl",
          "EAISDwoLU3lzdGVtRXJyb3IQAxIPCgtMb2dpbkZhaWxlZBAEEhgKFER1cGxp",
          "Y2F0ZV9FbnRlcl9Sb29tEAUqZwoRQ2FtZXJhQ29udHJvbFR5cGUSEAoMU3dp",
          "dGNoQ2FtZXJhEAASDQoJUXVhbGl0eVVwEAESDwoLUXVhbGl0eURvd24QAhIJ",
          "CgVGbGFzaBADEgwKCFNhdmVGaWxlEAQSBwoDTUlDEAVCAkgBYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::PROTOCOL), typeof(global::ErrorCode), typeof(global::CameraControlType), }, null, null));
  }
  #endregion

}
#region Enums
public enum PROTOCOL {
  [pbr::OriginalName("ID_PKT_VERSION_REQ")] IdPktVersionReq = 0,
  [pbr::OriginalName("ID_PKT_VERSION_RES")] IdPktVersionRes = 1,
  [pbr::OriginalName("ID_PKT_LOGIN_REQ")] IdPktLoginReq = 2,
  [pbr::OriginalName("ID_PKT_LOGIN_RES")] IdPktLoginRes = 3,
  [pbr::OriginalName("ID_PKT_CREATE_ROOM_REQ")] IdPktCreateRoomReq = 4,
  [pbr::OriginalName("ID_PKT_CREATE_ROOM_RES")] IdPktCreateRoomRes = 5,
  [pbr::OriginalName("ID_PKT_ENTER_ROOM_REQ")] IdPktEnterRoomReq = 6,
  [pbr::OriginalName("ID_PKT_ENTER_ROOM_RES")] IdPktEnterRoomRes = 7,
  [pbr::OriginalName("ID_PKT_LEAVE_ROOM_REQ")] IdPktLeaveRoomReq = 8,
  [pbr::OriginalName("ID_PKT_LEAVE_ROOM_RES")] IdPktLeaveRoomRes = 9,
  [pbr::OriginalName("ID_PKT_BITMAP_MESSAGE_REQ")] IdPktBitmapMessageReq = 10,
  [pbr::OriginalName("ID_PKT_BITMAP_MESSAGE_RES")] IdPktBitmapMessageRes = 11,
  [pbr::OriginalName("ID_PKT_NEW_USER_IN_ROOM_NTY")] IdPktNewUserInRoomNty = 12,
  [pbr::OriginalName("ID_PKT_ROOM_LIST_REQ")] IdPktRoomListReq = 13,
  [pbr::OriginalName("ID_PKT_ROOM_LIST_RES")] IdPktRoomListRes = 14,
  [pbr::OriginalName("ID_PKT_GAME_START_NTY")] IdPktGameStartNty = 15,
  [pbr::OriginalName("ID_PKT_GAME_RESULT_NTY")] IdPktGameResultNty = 16,
  [pbr::OriginalName("ID_PKT_ROOM_PASS_THROUGH_REQ")] IdPktRoomPassThroughReq = 17,
  [pbr::OriginalName("ID_PKT_ROOM_PASS_THROUGH_RES")] IdPktRoomPassThroughRes = 18,
  [pbr::OriginalName("ID_PKT_NOTICE_REQ")] IdPktNoticeReq = 19,
  [pbr::OriginalName("ID_PKT_NOTICE_RES")] IdPktNoticeRes = 20,
  [pbr::OriginalName("ID_PKT_AUDIO_MESSAGE_REQ")] IdPktAudioMessageReq = 21,
  [pbr::OriginalName("ID_PKT_AUDIO_MESSAGE_RES")] IdPktAudioMessageRes = 22,
  [pbr::OriginalName("ID_PKT_PRAY_MESSAGE_REQ")] IdPktPrayMessageReq = 23,
  [pbr::OriginalName("ID_PKT_PRAY_MESSAGE_RES")] IdPktPrayMessageRes = 24,
  [pbr::OriginalName("ID_PKT_PRAY_MESSAGE_REG_REQ")] IdPktPrayMessageRegReq = 25,
  [pbr::OriginalName("ID_PKT_PRAY_MESSAGE_REG_RES")] IdPktPrayMessageRegRes = 26,
  [pbr::OriginalName("ID_PKT_QNA_REQ")] IdPktQnaReq = 27,
  [pbr::OriginalName("ID_PKT_QNA_RES")] IdPktQnaRes = 28,
  [pbr::OriginalName("ID_PKT_MAIL_LIST_REQ")] IdPktMailListReq = 29,
  [pbr::OriginalName("ID_PKT_MAIL_LIST_RES")] IdPktMailListRes = 30,
  [pbr::OriginalName("ID_PKT_MAIL_SEND_REQ")] IdPktMailSendReq = 31,
  [pbr::OriginalName("ID_PKT_MAIL_SEND_RES")] IdPktMailSendRes = 32,
  [pbr::OriginalName("ID_PKT_MAIL_DEL_REQ")] IdPktMailDelReq = 33,
  [pbr::OriginalName("ID_PKT_MAIL_DEL_RES")] IdPktMailDelRes = 34,
  [pbr::OriginalName("ID_PKT_MAIL_READ_REQ")] IdPktMailReadReq = 35,
  [pbr::OriginalName("ID_PKT_MAIL_READ_RES")] IdPktMailReadRes = 36,
  [pbr::OriginalName("ID_PKT_REG_REQ")] IdPktRegReq = 37,
  [pbr::OriginalName("ID_PKT_REG_RES")] IdPktRegRes = 38,
  [pbr::OriginalName("ID_PKT_CLIENT_LOGOUT_REQ")] IdPktClientLogoutReq = 39,
  [pbr::OriginalName("ID_PKT_CLIENT_LOGOUT_RES")] IdPktClientLogoutRes = 40,
  [pbr::OriginalName("ID_PKT_CLIENT_KICK")] IdPktClientKick = 41,
  [pbr::OriginalName("ID_PKT_CAMERA_CONTROL_REQ")] IdPktCameraControlReq = 42,
  [pbr::OriginalName("ID_PKT_CAMERA_CONTROL_RES")] IdPktCameraControlRes = 43,
  [pbr::OriginalName("ID_PKT_MPEG2TS_MESSAGE_REQ")] IdPktMpeg2TsMessageReq = 44,
  [pbr::OriginalName("ID_PKT_MPEG2TS_MESSAGE_RES")] IdPktMpeg2TsMessageRes = 45,
  [pbr::OriginalName("ID_PKT_CAMERA_WAKE_UP_REQ")] IdPktCameraWakeUpReq = 46,
  [pbr::OriginalName("ID_PKT_CAMERA_WAKE_UP_RES")] IdPktCameraWakeUpRes = 47,
  [pbr::OriginalName("ID_PKT_STOP_STREAM_REQ")] IdPktStopStreamReq = 48,
  [pbr::OriginalName("ID_PKT_STOP_STREAM_RES")] IdPktStopStreamRes = 49,
  [pbr::OriginalName("ID_PKT_REG_CAMERA_REQ")] IdPktRegCameraReq = 50,
  [pbr::OriginalName("ID_PKT_REG_CAMERA_RES")] IdPktRegCameraRes = 51,
  [pbr::OriginalName("ID_PKT_CAMERA_LIST_REQ")] IdPktCameraListReq = 52,
  [pbr::OriginalName("ID_PKT_CAMERA_LIST_RES")] IdPktCameraListRes = 53,
  [pbr::OriginalName("ID_PKT_MACHINE_STATUS_REQ")] IdPktMachineStatusReq = 54,
  [pbr::OriginalName("ID_PKT_MACHINE_STATUS_RES")] IdPktMachineStatusRes = 55,
  [pbr::OriginalName("ID_PKT_VERIFY_PURCHASE_REQ")] IdPktVerifyPurchaseReq = 56,
  [pbr::OriginalName("ID_PKT_VERIFY_PURCHASE_RES")] IdPktVerifyPurchaseRes = 57,
  [pbr::OriginalName("ID_PKT_DEL_CAMERA_REQ")] IdPktDelCameraReq = 58,
  [pbr::OriginalName("ID_PKT_DEL_CAMERA_RES")] IdPktDelCameraRes = 59,
  [pbr::OriginalName("ID_PKT_RECONNECT_REQ")] IdPktReconnectReq = 60,
  [pbr::OriginalName("ID_PKT_RECONNECT_RES")] IdPktReconnectRes = 61,
}

public enum ErrorCode {
  [pbr::OriginalName("Success")] Success = 0,
  [pbr::OriginalName("DataBaseError")] DataBaseError = 1,
  [pbr::OriginalName("LoginDuplicate")] LoginDuplicate = 2,
  [pbr::OriginalName("SystemError")] SystemError = 3,
  [pbr::OriginalName("LoginFailed")] LoginFailed = 4,
  [pbr::OriginalName("Duplicate_Enter_Room")] DuplicateEnterRoom = 5,
}

public enum CameraControlType {
  [pbr::OriginalName("SwitchCamera")] SwitchCamera = 0,
  [pbr::OriginalName("QualityUp")] QualityUp = 1,
  [pbr::OriginalName("QualityDown")] QualityDown = 2,
  [pbr::OriginalName("Flash")] Flash = 3,
  [pbr::OriginalName("SaveFile")] SaveFile = 4,
  [pbr::OriginalName("MIC")] Mic = 5,
}

#endregion


#endregion Designer generated code
