// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Structure.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Structure_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Structure_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Structure_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Structure_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[6]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Structure_2eproto;
class MailInfo;
class MailInfoDefaultTypeInternal;
extern MailInfoDefaultTypeInternal _MailInfo_default_instance_;
class NotifyInfo;
class NotifyInfoDefaultTypeInternal;
extern NotifyInfoDefaultTypeInternal _NotifyInfo_default_instance_;
class PrayInfo;
class PrayInfoDefaultTypeInternal;
extern PrayInfoDefaultTypeInternal _PrayInfo_default_instance_;
class RoomInfo2;
class RoomInfo2DefaultTypeInternal;
extern RoomInfo2DefaultTypeInternal _RoomInfo2_default_instance_;
class RoomMessage;
class RoomMessageDefaultTypeInternal;
extern RoomMessageDefaultTypeInternal _RoomMessage_default_instance_;
class RoomUserInfo;
class RoomUserInfoDefaultTypeInternal;
extern RoomUserInfoDefaultTypeInternal _RoomUserInfo_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::MailInfo* Arena::CreateMaybeMessage<::MailInfo>(Arena*);
template<> ::NotifyInfo* Arena::CreateMaybeMessage<::NotifyInfo>(Arena*);
template<> ::PrayInfo* Arena::CreateMaybeMessage<::PrayInfo>(Arena*);
template<> ::RoomInfo2* Arena::CreateMaybeMessage<::RoomInfo2>(Arena*);
template<> ::RoomMessage* Arena::CreateMaybeMessage<::RoomMessage>(Arena*);
template<> ::RoomUserInfo* Arena::CreateMaybeMessage<::RoomUserInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class RoomUserInfo :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RoomUserInfo) */ {
 public:
  RoomUserInfo();
  virtual ~RoomUserInfo();

  RoomUserInfo(const RoomUserInfo& from);
  RoomUserInfo(RoomUserInfo&& from) noexcept
    : RoomUserInfo() {
    *this = ::std::move(from);
  }

  inline RoomUserInfo& operator=(const RoomUserInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoomUserInfo& operator=(RoomUserInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RoomUserInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RoomUserInfo* internal_default_instance() {
    return reinterpret_cast<const RoomUserInfo*>(
               &_RoomUserInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(RoomUserInfo& a, RoomUserInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(RoomUserInfo* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RoomUserInfo* New() const final {
    return CreateMaybeMessage<RoomUserInfo>(nullptr);
  }

  RoomUserInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RoomUserInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RoomUserInfo& from);
  void MergeFrom(const RoomUserInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoomUserInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RoomUserInfo";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Structure_2eproto);
    return ::descriptor_table_Structure_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVarNameFieldNumber = 1,
    kPictureUriFieldNumber = 3,
    kVarIndexFieldNumber = 2,
    kVarRoomNumberFieldNumber = 4,
  };
  // optional string var_name = 1;
  bool has_var_name() const;
  private:
  bool _internal_has_var_name() const;
  public:
  void clear_var_name();
  const std::string& var_name() const;
  void set_var_name(const std::string& value);
  void set_var_name(std::string&& value);
  void set_var_name(const char* value);
  void set_var_name(const char* value, size_t size);
  std::string* mutable_var_name();
  std::string* release_var_name();
  void set_allocated_var_name(std::string* var_name);
  private:
  const std::string& _internal_var_name() const;
  void _internal_set_var_name(const std::string& value);
  std::string* _internal_mutable_var_name();
  public:

  // optional string picture_uri = 3;
  bool has_picture_uri() const;
  private:
  bool _internal_has_picture_uri() const;
  public:
  void clear_picture_uri();
  const std::string& picture_uri() const;
  void set_picture_uri(const std::string& value);
  void set_picture_uri(std::string&& value);
  void set_picture_uri(const char* value);
  void set_picture_uri(const char* value, size_t size);
  std::string* mutable_picture_uri();
  std::string* release_picture_uri();
  void set_allocated_picture_uri(std::string* picture_uri);
  private:
  const std::string& _internal_picture_uri() const;
  void _internal_set_picture_uri(const std::string& value);
  std::string* _internal_mutable_picture_uri();
  public:

  // optional int64 var_index = 2;
  bool has_var_index() const;
  private:
  bool _internal_has_var_index() const;
  public:
  void clear_var_index();
  ::PROTOBUF_NAMESPACE_ID::int64 var_index() const;
  void set_var_index(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_var_index() const;
  void _internal_set_var_index(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // optional int32 var_room_number = 4;
  bool has_var_room_number() const;
  private:
  bool _internal_has_var_room_number() const;
  public:
  void clear_var_room_number();
  ::PROTOBUF_NAMESPACE_ID::int32 var_room_number() const;
  void set_var_room_number(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_var_room_number() const;
  void _internal_set_var_room_number(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:RoomUserInfo)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr var_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr picture_uri_;
  ::PROTOBUF_NAMESPACE_ID::int64 var_index_;
  ::PROTOBUF_NAMESPACE_ID::int32 var_room_number_;
  friend struct ::TableStruct_Structure_2eproto;
};
// -------------------------------------------------------------------

class RoomInfo2 :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RoomInfo2) */ {
 public:
  RoomInfo2();
  virtual ~RoomInfo2();

  RoomInfo2(const RoomInfo2& from);
  RoomInfo2(RoomInfo2&& from) noexcept
    : RoomInfo2() {
    *this = ::std::move(from);
  }

  inline RoomInfo2& operator=(const RoomInfo2& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoomInfo2& operator=(RoomInfo2&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RoomInfo2& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RoomInfo2* internal_default_instance() {
    return reinterpret_cast<const RoomInfo2*>(
               &_RoomInfo2_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(RoomInfo2& a, RoomInfo2& b) {
    a.Swap(&b);
  }
  inline void Swap(RoomInfo2* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RoomInfo2* New() const final {
    return CreateMaybeMessage<RoomInfo2>(nullptr);
  }

  RoomInfo2* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RoomInfo2>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RoomInfo2& from);
  void MergeFrom(const RoomInfo2& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoomInfo2* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RoomInfo2";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Structure_2eproto);
    return ::descriptor_table_Structure_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVarNameFieldNumber = 2,
    kVarIdFieldNumber = 1,
    kVarCurrentCountFieldNumber = 3,
    kVarMaxCountFieldNumber = 4,
  };
  // optional string var_name = 2;
  bool has_var_name() const;
  private:
  bool _internal_has_var_name() const;
  public:
  void clear_var_name();
  const std::string& var_name() const;
  void set_var_name(const std::string& value);
  void set_var_name(std::string&& value);
  void set_var_name(const char* value);
  void set_var_name(const char* value, size_t size);
  std::string* mutable_var_name();
  std::string* release_var_name();
  void set_allocated_var_name(std::string* var_name);
  private:
  const std::string& _internal_var_name() const;
  void _internal_set_var_name(const std::string& value);
  std::string* _internal_mutable_var_name();
  public:

  // optional int32 var_id = 1;
  bool has_var_id() const;
  private:
  bool _internal_has_var_id() const;
  public:
  void clear_var_id();
  ::PROTOBUF_NAMESPACE_ID::int32 var_id() const;
  void set_var_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_var_id() const;
  void _internal_set_var_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional int32 var_current_count = 3;
  bool has_var_current_count() const;
  private:
  bool _internal_has_var_current_count() const;
  public:
  void clear_var_current_count();
  ::PROTOBUF_NAMESPACE_ID::int32 var_current_count() const;
  void set_var_current_count(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_var_current_count() const;
  void _internal_set_var_current_count(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // optional int32 var_max_count = 4;
  bool has_var_max_count() const;
  private:
  bool _internal_has_var_max_count() const;
  public:
  void clear_var_max_count();
  ::PROTOBUF_NAMESPACE_ID::int32 var_max_count() const;
  void set_var_max_count(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_var_max_count() const;
  void _internal_set_var_max_count(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:RoomInfo2)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr var_name_;
  ::PROTOBUF_NAMESPACE_ID::int32 var_id_;
  ::PROTOBUF_NAMESPACE_ID::int32 var_current_count_;
  ::PROTOBUF_NAMESPACE_ID::int32 var_max_count_;
  friend struct ::TableStruct_Structure_2eproto;
};
// -------------------------------------------------------------------

class PrayInfo :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:PrayInfo) */ {
 public:
  PrayInfo();
  virtual ~PrayInfo();

  PrayInfo(const PrayInfo& from);
  PrayInfo(PrayInfo&& from) noexcept
    : PrayInfo() {
    *this = ::std::move(from);
  }

  inline PrayInfo& operator=(const PrayInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline PrayInfo& operator=(PrayInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PrayInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PrayInfo* internal_default_instance() {
    return reinterpret_cast<const PrayInfo*>(
               &_PrayInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PrayInfo& a, PrayInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(PrayInfo* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PrayInfo* New() const final {
    return CreateMaybeMessage<PrayInfo>(nullptr);
  }

  PrayInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PrayInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PrayInfo& from);
  void MergeFrom(const PrayInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PrayInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "PrayInfo";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Structure_2eproto);
    return ::descriptor_table_Structure_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVarNameFieldNumber = 1,
    kVarMessageFieldNumber = 2,
    kVarTimeFieldNumber = 3,
  };
  // optional string var_name = 1;
  bool has_var_name() const;
  private:
  bool _internal_has_var_name() const;
  public:
  void clear_var_name();
  const std::string& var_name() const;
  void set_var_name(const std::string& value);
  void set_var_name(std::string&& value);
  void set_var_name(const char* value);
  void set_var_name(const char* value, size_t size);
  std::string* mutable_var_name();
  std::string* release_var_name();
  void set_allocated_var_name(std::string* var_name);
  private:
  const std::string& _internal_var_name() const;
  void _internal_set_var_name(const std::string& value);
  std::string* _internal_mutable_var_name();
  public:

  // optional string var_message = 2;
  bool has_var_message() const;
  private:
  bool _internal_has_var_message() const;
  public:
  void clear_var_message();
  const std::string& var_message() const;
  void set_var_message(const std::string& value);
  void set_var_message(std::string&& value);
  void set_var_message(const char* value);
  void set_var_message(const char* value, size_t size);
  std::string* mutable_var_message();
  std::string* release_var_message();
  void set_allocated_var_message(std::string* var_message);
  private:
  const std::string& _internal_var_message() const;
  void _internal_set_var_message(const std::string& value);
  std::string* _internal_mutable_var_message();
  public:

  // optional string var_time = 3;
  bool has_var_time() const;
  private:
  bool _internal_has_var_time() const;
  public:
  void clear_var_time();
  const std::string& var_time() const;
  void set_var_time(const std::string& value);
  void set_var_time(std::string&& value);
  void set_var_time(const char* value);
  void set_var_time(const char* value, size_t size);
  std::string* mutable_var_time();
  std::string* release_var_time();
  void set_allocated_var_time(std::string* var_time);
  private:
  const std::string& _internal_var_time() const;
  void _internal_set_var_time(const std::string& value);
  std::string* _internal_mutable_var_time();
  public:

  // @@protoc_insertion_point(class_scope:PrayInfo)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr var_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr var_message_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr var_time_;
  friend struct ::TableStruct_Structure_2eproto;
};
// -------------------------------------------------------------------

class NotifyInfo :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:NotifyInfo) */ {
 public:
  NotifyInfo();
  virtual ~NotifyInfo();

  NotifyInfo(const NotifyInfo& from);
  NotifyInfo(NotifyInfo&& from) noexcept
    : NotifyInfo() {
    *this = ::std::move(from);
  }

  inline NotifyInfo& operator=(const NotifyInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline NotifyInfo& operator=(NotifyInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const NotifyInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NotifyInfo* internal_default_instance() {
    return reinterpret_cast<const NotifyInfo*>(
               &_NotifyInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(NotifyInfo& a, NotifyInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(NotifyInfo* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline NotifyInfo* New() const final {
    return CreateMaybeMessage<NotifyInfo>(nullptr);
  }

  NotifyInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<NotifyInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const NotifyInfo& from);
  void MergeFrom(const NotifyInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NotifyInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "NotifyInfo";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Structure_2eproto);
    return ::descriptor_table_Structure_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVarContentFieldNumber = 2,
    kVarDateFieldNumber = 3,
    kVarIdFieldNumber = 1,
  };
  // optional string var_content = 2;
  bool has_var_content() const;
  private:
  bool _internal_has_var_content() const;
  public:
  void clear_var_content();
  const std::string& var_content() const;
  void set_var_content(const std::string& value);
  void set_var_content(std::string&& value);
  void set_var_content(const char* value);
  void set_var_content(const char* value, size_t size);
  std::string* mutable_var_content();
  std::string* release_var_content();
  void set_allocated_var_content(std::string* var_content);
  private:
  const std::string& _internal_var_content() const;
  void _internal_set_var_content(const std::string& value);
  std::string* _internal_mutable_var_content();
  public:

  // optional string var_date = 3;
  bool has_var_date() const;
  private:
  bool _internal_has_var_date() const;
  public:
  void clear_var_date();
  const std::string& var_date() const;
  void set_var_date(const std::string& value);
  void set_var_date(std::string&& value);
  void set_var_date(const char* value);
  void set_var_date(const char* value, size_t size);
  std::string* mutable_var_date();
  std::string* release_var_date();
  void set_allocated_var_date(std::string* var_date);
  private:
  const std::string& _internal_var_date() const;
  void _internal_set_var_date(const std::string& value);
  std::string* _internal_mutable_var_date();
  public:

  // optional int64 var_id = 1;
  bool has_var_id() const;
  private:
  bool _internal_has_var_id() const;
  public:
  void clear_var_id();
  ::PROTOBUF_NAMESPACE_ID::int64 var_id() const;
  void set_var_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_var_id() const;
  void _internal_set_var_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:NotifyInfo)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr var_content_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr var_date_;
  ::PROTOBUF_NAMESPACE_ID::int64 var_id_;
  friend struct ::TableStruct_Structure_2eproto;
};
// -------------------------------------------------------------------

class MailInfo :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:MailInfo) */ {
 public:
  MailInfo();
  virtual ~MailInfo();

  MailInfo(const MailInfo& from);
  MailInfo(MailInfo&& from) noexcept
    : MailInfo() {
    *this = ::std::move(from);
  }

  inline MailInfo& operator=(const MailInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline MailInfo& operator=(MailInfo&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MailInfo& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MailInfo* internal_default_instance() {
    return reinterpret_cast<const MailInfo*>(
               &_MailInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(MailInfo& a, MailInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(MailInfo* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MailInfo* New() const final {
    return CreateMaybeMessage<MailInfo>(nullptr);
  }

  MailInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MailInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MailInfo& from);
  void MergeFrom(const MailInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MailInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "MailInfo";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Structure_2eproto);
    return ::descriptor_table_Structure_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVarTitleFieldNumber = 2,
    kVarContentFieldNumber = 3,
    kVarDateFieldNumber = 4,
    kVarNameFieldNumber = 5,
    kVarIdFieldNumber = 1,
  };
  // optional string var_title = 2;
  bool has_var_title() const;
  private:
  bool _internal_has_var_title() const;
  public:
  void clear_var_title();
  const std::string& var_title() const;
  void set_var_title(const std::string& value);
  void set_var_title(std::string&& value);
  void set_var_title(const char* value);
  void set_var_title(const char* value, size_t size);
  std::string* mutable_var_title();
  std::string* release_var_title();
  void set_allocated_var_title(std::string* var_title);
  private:
  const std::string& _internal_var_title() const;
  void _internal_set_var_title(const std::string& value);
  std::string* _internal_mutable_var_title();
  public:

  // optional string var_content = 3;
  bool has_var_content() const;
  private:
  bool _internal_has_var_content() const;
  public:
  void clear_var_content();
  const std::string& var_content() const;
  void set_var_content(const std::string& value);
  void set_var_content(std::string&& value);
  void set_var_content(const char* value);
  void set_var_content(const char* value, size_t size);
  std::string* mutable_var_content();
  std::string* release_var_content();
  void set_allocated_var_content(std::string* var_content);
  private:
  const std::string& _internal_var_content() const;
  void _internal_set_var_content(const std::string& value);
  std::string* _internal_mutable_var_content();
  public:

  // optional string var_date = 4;
  bool has_var_date() const;
  private:
  bool _internal_has_var_date() const;
  public:
  void clear_var_date();
  const std::string& var_date() const;
  void set_var_date(const std::string& value);
  void set_var_date(std::string&& value);
  void set_var_date(const char* value);
  void set_var_date(const char* value, size_t size);
  std::string* mutable_var_date();
  std::string* release_var_date();
  void set_allocated_var_date(std::string* var_date);
  private:
  const std::string& _internal_var_date() const;
  void _internal_set_var_date(const std::string& value);
  std::string* _internal_mutable_var_date();
  public:

  // optional string var_name = 5;
  bool has_var_name() const;
  private:
  bool _internal_has_var_name() const;
  public:
  void clear_var_name();
  const std::string& var_name() const;
  void set_var_name(const std::string& value);
  void set_var_name(std::string&& value);
  void set_var_name(const char* value);
  void set_var_name(const char* value, size_t size);
  std::string* mutable_var_name();
  std::string* release_var_name();
  void set_allocated_var_name(std::string* var_name);
  private:
  const std::string& _internal_var_name() const;
  void _internal_set_var_name(const std::string& value);
  std::string* _internal_mutable_var_name();
  public:

  // optional int64 var_id = 1;
  bool has_var_id() const;
  private:
  bool _internal_has_var_id() const;
  public:
  void clear_var_id();
  ::PROTOBUF_NAMESPACE_ID::int64 var_id() const;
  void set_var_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int64 _internal_var_id() const;
  void _internal_set_var_id(::PROTOBUF_NAMESPACE_ID::int64 value);
  public:

  // @@protoc_insertion_point(class_scope:MailInfo)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr var_title_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr var_content_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr var_date_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr var_name_;
  ::PROTOBUF_NAMESPACE_ID::int64 var_id_;
  friend struct ::TableStruct_Structure_2eproto;
};
// -------------------------------------------------------------------

class RoomMessage :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:RoomMessage) */ {
 public:
  RoomMessage();
  virtual ~RoomMessage();

  RoomMessage(const RoomMessage& from);
  RoomMessage(RoomMessage&& from) noexcept
    : RoomMessage() {
    *this = ::std::move(from);
  }

  inline RoomMessage& operator=(const RoomMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline RoomMessage& operator=(RoomMessage&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RoomMessage& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RoomMessage* internal_default_instance() {
    return reinterpret_cast<const RoomMessage*>(
               &_RoomMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(RoomMessage& a, RoomMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(RoomMessage* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RoomMessage* New() const final {
    return CreateMaybeMessage<RoomMessage>(nullptr);
  }

  RoomMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RoomMessage>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RoomMessage& from);
  void MergeFrom(const RoomMessage& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RoomMessage* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "RoomMessage";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Structure_2eproto);
    return ::descriptor_table_Structure_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVarNameFieldNumber = 1,
    kVarMessageFieldNumber = 2,
    kVarTimeFieldNumber = 4,
    kVarMessageIntFieldNumber = 3,
  };
  // optional string var_name = 1;
  bool has_var_name() const;
  private:
  bool _internal_has_var_name() const;
  public:
  void clear_var_name();
  const std::string& var_name() const;
  void set_var_name(const std::string& value);
  void set_var_name(std::string&& value);
  void set_var_name(const char* value);
  void set_var_name(const char* value, size_t size);
  std::string* mutable_var_name();
  std::string* release_var_name();
  void set_allocated_var_name(std::string* var_name);
  private:
  const std::string& _internal_var_name() const;
  void _internal_set_var_name(const std::string& value);
  std::string* _internal_mutable_var_name();
  public:

  // optional string var_message = 2;
  bool has_var_message() const;
  private:
  bool _internal_has_var_message() const;
  public:
  void clear_var_message();
  const std::string& var_message() const;
  void set_var_message(const std::string& value);
  void set_var_message(std::string&& value);
  void set_var_message(const char* value);
  void set_var_message(const char* value, size_t size);
  std::string* mutable_var_message();
  std::string* release_var_message();
  void set_allocated_var_message(std::string* var_message);
  private:
  const std::string& _internal_var_message() const;
  void _internal_set_var_message(const std::string& value);
  std::string* _internal_mutable_var_message();
  public:

  // optional string var_time = 4;
  bool has_var_time() const;
  private:
  bool _internal_has_var_time() const;
  public:
  void clear_var_time();
  const std::string& var_time() const;
  void set_var_time(const std::string& value);
  void set_var_time(std::string&& value);
  void set_var_time(const char* value);
  void set_var_time(const char* value, size_t size);
  std::string* mutable_var_time();
  std::string* release_var_time();
  void set_allocated_var_time(std::string* var_time);
  private:
  const std::string& _internal_var_time() const;
  void _internal_set_var_time(const std::string& value);
  std::string* _internal_mutable_var_time();
  public:

  // optional int32 var_message_int = 3;
  bool has_var_message_int() const;
  private:
  bool _internal_has_var_message_int() const;
  public:
  void clear_var_message_int();
  ::PROTOBUF_NAMESPACE_ID::int32 var_message_int() const;
  void set_var_message_int(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_var_message_int() const;
  void _internal_set_var_message_int(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:RoomMessage)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr var_name_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr var_message_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr var_time_;
  ::PROTOBUF_NAMESPACE_ID::int32 var_message_int_;
  friend struct ::TableStruct_Structure_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RoomUserInfo

// optional string var_name = 1;
inline bool RoomUserInfo::_internal_has_var_name() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool RoomUserInfo::has_var_name() const {
  return _internal_has_var_name();
}
inline void RoomUserInfo::clear_var_name() {
  var_name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& RoomUserInfo::var_name() const {
  // @@protoc_insertion_point(field_get:RoomUserInfo.var_name)
  return _internal_var_name();
}
inline void RoomUserInfo::set_var_name(const std::string& value) {
  _internal_set_var_name(value);
  // @@protoc_insertion_point(field_set:RoomUserInfo.var_name)
}
inline std::string* RoomUserInfo::mutable_var_name() {
  // @@protoc_insertion_point(field_mutable:RoomUserInfo.var_name)
  return _internal_mutable_var_name();
}
inline const std::string& RoomUserInfo::_internal_var_name() const {
  return var_name_.GetNoArena();
}
inline void RoomUserInfo::_internal_set_var_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  var_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void RoomUserInfo::set_var_name(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  var_name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:RoomUserInfo.var_name)
}
inline void RoomUserInfo::set_var_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  var_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:RoomUserInfo.var_name)
}
inline void RoomUserInfo::set_var_name(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  var_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:RoomUserInfo.var_name)
}
inline std::string* RoomUserInfo::_internal_mutable_var_name() {
  _has_bits_[0] |= 0x00000001u;
  return var_name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* RoomUserInfo::release_var_name() {
  // @@protoc_insertion_point(field_release:RoomUserInfo.var_name)
  if (!_internal_has_var_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return var_name_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void RoomUserInfo::set_allocated_var_name(std::string* var_name) {
  if (var_name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  var_name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), var_name);
  // @@protoc_insertion_point(field_set_allocated:RoomUserInfo.var_name)
}

// optional int64 var_index = 2;
inline bool RoomUserInfo::_internal_has_var_index() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool RoomUserInfo::has_var_index() const {
  return _internal_has_var_index();
}
inline void RoomUserInfo::clear_var_index() {
  var_index_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 RoomUserInfo::_internal_var_index() const {
  return var_index_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 RoomUserInfo::var_index() const {
  // @@protoc_insertion_point(field_get:RoomUserInfo.var_index)
  return _internal_var_index();
}
inline void RoomUserInfo::_internal_set_var_index(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000004u;
  var_index_ = value;
}
inline void RoomUserInfo::set_var_index(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_var_index(value);
  // @@protoc_insertion_point(field_set:RoomUserInfo.var_index)
}

// optional string picture_uri = 3;
inline bool RoomUserInfo::_internal_has_picture_uri() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool RoomUserInfo::has_picture_uri() const {
  return _internal_has_picture_uri();
}
inline void RoomUserInfo::clear_picture_uri() {
  picture_uri_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& RoomUserInfo::picture_uri() const {
  // @@protoc_insertion_point(field_get:RoomUserInfo.picture_uri)
  return _internal_picture_uri();
}
inline void RoomUserInfo::set_picture_uri(const std::string& value) {
  _internal_set_picture_uri(value);
  // @@protoc_insertion_point(field_set:RoomUserInfo.picture_uri)
}
inline std::string* RoomUserInfo::mutable_picture_uri() {
  // @@protoc_insertion_point(field_mutable:RoomUserInfo.picture_uri)
  return _internal_mutable_picture_uri();
}
inline const std::string& RoomUserInfo::_internal_picture_uri() const {
  return picture_uri_.GetNoArena();
}
inline void RoomUserInfo::_internal_set_picture_uri(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  picture_uri_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void RoomUserInfo::set_picture_uri(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  picture_uri_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:RoomUserInfo.picture_uri)
}
inline void RoomUserInfo::set_picture_uri(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  picture_uri_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:RoomUserInfo.picture_uri)
}
inline void RoomUserInfo::set_picture_uri(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000002u;
  picture_uri_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:RoomUserInfo.picture_uri)
}
inline std::string* RoomUserInfo::_internal_mutable_picture_uri() {
  _has_bits_[0] |= 0x00000002u;
  return picture_uri_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* RoomUserInfo::release_picture_uri() {
  // @@protoc_insertion_point(field_release:RoomUserInfo.picture_uri)
  if (!_internal_has_picture_uri()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return picture_uri_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void RoomUserInfo::set_allocated_picture_uri(std::string* picture_uri) {
  if (picture_uri != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  picture_uri_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), picture_uri);
  // @@protoc_insertion_point(field_set_allocated:RoomUserInfo.picture_uri)
}

// optional int32 var_room_number = 4;
inline bool RoomUserInfo::_internal_has_var_room_number() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool RoomUserInfo::has_var_room_number() const {
  return _internal_has_var_room_number();
}
inline void RoomUserInfo::clear_var_room_number() {
  var_room_number_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RoomUserInfo::_internal_var_room_number() const {
  return var_room_number_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RoomUserInfo::var_room_number() const {
  // @@protoc_insertion_point(field_get:RoomUserInfo.var_room_number)
  return _internal_var_room_number();
}
inline void RoomUserInfo::_internal_set_var_room_number(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000008u;
  var_room_number_ = value;
}
inline void RoomUserInfo::set_var_room_number(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_var_room_number(value);
  // @@protoc_insertion_point(field_set:RoomUserInfo.var_room_number)
}

// -------------------------------------------------------------------

// RoomInfo2

// optional int32 var_id = 1;
inline bool RoomInfo2::_internal_has_var_id() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool RoomInfo2::has_var_id() const {
  return _internal_has_var_id();
}
inline void RoomInfo2::clear_var_id() {
  var_id_ = 0;
  _has_bits_[0] &= ~0x00000002u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RoomInfo2::_internal_var_id() const {
  return var_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RoomInfo2::var_id() const {
  // @@protoc_insertion_point(field_get:RoomInfo2.var_id)
  return _internal_var_id();
}
inline void RoomInfo2::_internal_set_var_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000002u;
  var_id_ = value;
}
inline void RoomInfo2::set_var_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_var_id(value);
  // @@protoc_insertion_point(field_set:RoomInfo2.var_id)
}

// optional string var_name = 2;
inline bool RoomInfo2::_internal_has_var_name() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool RoomInfo2::has_var_name() const {
  return _internal_has_var_name();
}
inline void RoomInfo2::clear_var_name() {
  var_name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& RoomInfo2::var_name() const {
  // @@protoc_insertion_point(field_get:RoomInfo2.var_name)
  return _internal_var_name();
}
inline void RoomInfo2::set_var_name(const std::string& value) {
  _internal_set_var_name(value);
  // @@protoc_insertion_point(field_set:RoomInfo2.var_name)
}
inline std::string* RoomInfo2::mutable_var_name() {
  // @@protoc_insertion_point(field_mutable:RoomInfo2.var_name)
  return _internal_mutable_var_name();
}
inline const std::string& RoomInfo2::_internal_var_name() const {
  return var_name_.GetNoArena();
}
inline void RoomInfo2::_internal_set_var_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  var_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void RoomInfo2::set_var_name(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  var_name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:RoomInfo2.var_name)
}
inline void RoomInfo2::set_var_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  var_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:RoomInfo2.var_name)
}
inline void RoomInfo2::set_var_name(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  var_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:RoomInfo2.var_name)
}
inline std::string* RoomInfo2::_internal_mutable_var_name() {
  _has_bits_[0] |= 0x00000001u;
  return var_name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* RoomInfo2::release_var_name() {
  // @@protoc_insertion_point(field_release:RoomInfo2.var_name)
  if (!_internal_has_var_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return var_name_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void RoomInfo2::set_allocated_var_name(std::string* var_name) {
  if (var_name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  var_name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), var_name);
  // @@protoc_insertion_point(field_set_allocated:RoomInfo2.var_name)
}

// optional int32 var_current_count = 3;
inline bool RoomInfo2::_internal_has_var_current_count() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool RoomInfo2::has_var_current_count() const {
  return _internal_has_var_current_count();
}
inline void RoomInfo2::clear_var_current_count() {
  var_current_count_ = 0;
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RoomInfo2::_internal_var_current_count() const {
  return var_current_count_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RoomInfo2::var_current_count() const {
  // @@protoc_insertion_point(field_get:RoomInfo2.var_current_count)
  return _internal_var_current_count();
}
inline void RoomInfo2::_internal_set_var_current_count(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000004u;
  var_current_count_ = value;
}
inline void RoomInfo2::set_var_current_count(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_var_current_count(value);
  // @@protoc_insertion_point(field_set:RoomInfo2.var_current_count)
}

// optional int32 var_max_count = 4;
inline bool RoomInfo2::_internal_has_var_max_count() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool RoomInfo2::has_var_max_count() const {
  return _internal_has_var_max_count();
}
inline void RoomInfo2::clear_var_max_count() {
  var_max_count_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RoomInfo2::_internal_var_max_count() const {
  return var_max_count_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RoomInfo2::var_max_count() const {
  // @@protoc_insertion_point(field_get:RoomInfo2.var_max_count)
  return _internal_var_max_count();
}
inline void RoomInfo2::_internal_set_var_max_count(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000008u;
  var_max_count_ = value;
}
inline void RoomInfo2::set_var_max_count(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_var_max_count(value);
  // @@protoc_insertion_point(field_set:RoomInfo2.var_max_count)
}

// -------------------------------------------------------------------

// PrayInfo

// optional string var_name = 1;
inline bool PrayInfo::_internal_has_var_name() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool PrayInfo::has_var_name() const {
  return _internal_has_var_name();
}
inline void PrayInfo::clear_var_name() {
  var_name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& PrayInfo::var_name() const {
  // @@protoc_insertion_point(field_get:PrayInfo.var_name)
  return _internal_var_name();
}
inline void PrayInfo::set_var_name(const std::string& value) {
  _internal_set_var_name(value);
  // @@protoc_insertion_point(field_set:PrayInfo.var_name)
}
inline std::string* PrayInfo::mutable_var_name() {
  // @@protoc_insertion_point(field_mutable:PrayInfo.var_name)
  return _internal_mutable_var_name();
}
inline const std::string& PrayInfo::_internal_var_name() const {
  return var_name_.GetNoArena();
}
inline void PrayInfo::_internal_set_var_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  var_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void PrayInfo::set_var_name(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  var_name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PrayInfo.var_name)
}
inline void PrayInfo::set_var_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  var_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PrayInfo.var_name)
}
inline void PrayInfo::set_var_name(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  var_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PrayInfo.var_name)
}
inline std::string* PrayInfo::_internal_mutable_var_name() {
  _has_bits_[0] |= 0x00000001u;
  return var_name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* PrayInfo::release_var_name() {
  // @@protoc_insertion_point(field_release:PrayInfo.var_name)
  if (!_internal_has_var_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return var_name_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void PrayInfo::set_allocated_var_name(std::string* var_name) {
  if (var_name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  var_name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), var_name);
  // @@protoc_insertion_point(field_set_allocated:PrayInfo.var_name)
}

// optional string var_message = 2;
inline bool PrayInfo::_internal_has_var_message() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool PrayInfo::has_var_message() const {
  return _internal_has_var_message();
}
inline void PrayInfo::clear_var_message() {
  var_message_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& PrayInfo::var_message() const {
  // @@protoc_insertion_point(field_get:PrayInfo.var_message)
  return _internal_var_message();
}
inline void PrayInfo::set_var_message(const std::string& value) {
  _internal_set_var_message(value);
  // @@protoc_insertion_point(field_set:PrayInfo.var_message)
}
inline std::string* PrayInfo::mutable_var_message() {
  // @@protoc_insertion_point(field_mutable:PrayInfo.var_message)
  return _internal_mutable_var_message();
}
inline const std::string& PrayInfo::_internal_var_message() const {
  return var_message_.GetNoArena();
}
inline void PrayInfo::_internal_set_var_message(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  var_message_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void PrayInfo::set_var_message(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  var_message_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PrayInfo.var_message)
}
inline void PrayInfo::set_var_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  var_message_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PrayInfo.var_message)
}
inline void PrayInfo::set_var_message(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000002u;
  var_message_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PrayInfo.var_message)
}
inline std::string* PrayInfo::_internal_mutable_var_message() {
  _has_bits_[0] |= 0x00000002u;
  return var_message_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* PrayInfo::release_var_message() {
  // @@protoc_insertion_point(field_release:PrayInfo.var_message)
  if (!_internal_has_var_message()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return var_message_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void PrayInfo::set_allocated_var_message(std::string* var_message) {
  if (var_message != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  var_message_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), var_message);
  // @@protoc_insertion_point(field_set_allocated:PrayInfo.var_message)
}

// optional string var_time = 3;
inline bool PrayInfo::_internal_has_var_time() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool PrayInfo::has_var_time() const {
  return _internal_has_var_time();
}
inline void PrayInfo::clear_var_time() {
  var_time_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& PrayInfo::var_time() const {
  // @@protoc_insertion_point(field_get:PrayInfo.var_time)
  return _internal_var_time();
}
inline void PrayInfo::set_var_time(const std::string& value) {
  _internal_set_var_time(value);
  // @@protoc_insertion_point(field_set:PrayInfo.var_time)
}
inline std::string* PrayInfo::mutable_var_time() {
  // @@protoc_insertion_point(field_mutable:PrayInfo.var_time)
  return _internal_mutable_var_time();
}
inline const std::string& PrayInfo::_internal_var_time() const {
  return var_time_.GetNoArena();
}
inline void PrayInfo::_internal_set_var_time(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  var_time_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void PrayInfo::set_var_time(std::string&& value) {
  _has_bits_[0] |= 0x00000004u;
  var_time_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:PrayInfo.var_time)
}
inline void PrayInfo::set_var_time(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000004u;
  var_time_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PrayInfo.var_time)
}
inline void PrayInfo::set_var_time(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000004u;
  var_time_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PrayInfo.var_time)
}
inline std::string* PrayInfo::_internal_mutable_var_time() {
  _has_bits_[0] |= 0x00000004u;
  return var_time_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* PrayInfo::release_var_time() {
  // @@protoc_insertion_point(field_release:PrayInfo.var_time)
  if (!_internal_has_var_time()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  return var_time_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void PrayInfo::set_allocated_var_time(std::string* var_time) {
  if (var_time != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  var_time_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), var_time);
  // @@protoc_insertion_point(field_set_allocated:PrayInfo.var_time)
}

// -------------------------------------------------------------------

// NotifyInfo

// optional int64 var_id = 1;
inline bool NotifyInfo::_internal_has_var_id() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool NotifyInfo::has_var_id() const {
  return _internal_has_var_id();
}
inline void NotifyInfo::clear_var_id() {
  var_id_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000004u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 NotifyInfo::_internal_var_id() const {
  return var_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 NotifyInfo::var_id() const {
  // @@protoc_insertion_point(field_get:NotifyInfo.var_id)
  return _internal_var_id();
}
inline void NotifyInfo::_internal_set_var_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000004u;
  var_id_ = value;
}
inline void NotifyInfo::set_var_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_var_id(value);
  // @@protoc_insertion_point(field_set:NotifyInfo.var_id)
}

// optional string var_content = 2;
inline bool NotifyInfo::_internal_has_var_content() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool NotifyInfo::has_var_content() const {
  return _internal_has_var_content();
}
inline void NotifyInfo::clear_var_content() {
  var_content_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& NotifyInfo::var_content() const {
  // @@protoc_insertion_point(field_get:NotifyInfo.var_content)
  return _internal_var_content();
}
inline void NotifyInfo::set_var_content(const std::string& value) {
  _internal_set_var_content(value);
  // @@protoc_insertion_point(field_set:NotifyInfo.var_content)
}
inline std::string* NotifyInfo::mutable_var_content() {
  // @@protoc_insertion_point(field_mutable:NotifyInfo.var_content)
  return _internal_mutable_var_content();
}
inline const std::string& NotifyInfo::_internal_var_content() const {
  return var_content_.GetNoArena();
}
inline void NotifyInfo::_internal_set_var_content(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  var_content_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void NotifyInfo::set_var_content(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  var_content_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:NotifyInfo.var_content)
}
inline void NotifyInfo::set_var_content(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  var_content_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:NotifyInfo.var_content)
}
inline void NotifyInfo::set_var_content(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  var_content_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:NotifyInfo.var_content)
}
inline std::string* NotifyInfo::_internal_mutable_var_content() {
  _has_bits_[0] |= 0x00000001u;
  return var_content_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* NotifyInfo::release_var_content() {
  // @@protoc_insertion_point(field_release:NotifyInfo.var_content)
  if (!_internal_has_var_content()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return var_content_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void NotifyInfo::set_allocated_var_content(std::string* var_content) {
  if (var_content != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  var_content_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), var_content);
  // @@protoc_insertion_point(field_set_allocated:NotifyInfo.var_content)
}

// optional string var_date = 3;
inline bool NotifyInfo::_internal_has_var_date() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool NotifyInfo::has_var_date() const {
  return _internal_has_var_date();
}
inline void NotifyInfo::clear_var_date() {
  var_date_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& NotifyInfo::var_date() const {
  // @@protoc_insertion_point(field_get:NotifyInfo.var_date)
  return _internal_var_date();
}
inline void NotifyInfo::set_var_date(const std::string& value) {
  _internal_set_var_date(value);
  // @@protoc_insertion_point(field_set:NotifyInfo.var_date)
}
inline std::string* NotifyInfo::mutable_var_date() {
  // @@protoc_insertion_point(field_mutable:NotifyInfo.var_date)
  return _internal_mutable_var_date();
}
inline const std::string& NotifyInfo::_internal_var_date() const {
  return var_date_.GetNoArena();
}
inline void NotifyInfo::_internal_set_var_date(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  var_date_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void NotifyInfo::set_var_date(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  var_date_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:NotifyInfo.var_date)
}
inline void NotifyInfo::set_var_date(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  var_date_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:NotifyInfo.var_date)
}
inline void NotifyInfo::set_var_date(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000002u;
  var_date_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:NotifyInfo.var_date)
}
inline std::string* NotifyInfo::_internal_mutable_var_date() {
  _has_bits_[0] |= 0x00000002u;
  return var_date_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* NotifyInfo::release_var_date() {
  // @@protoc_insertion_point(field_release:NotifyInfo.var_date)
  if (!_internal_has_var_date()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return var_date_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void NotifyInfo::set_allocated_var_date(std::string* var_date) {
  if (var_date != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  var_date_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), var_date);
  // @@protoc_insertion_point(field_set_allocated:NotifyInfo.var_date)
}

// -------------------------------------------------------------------

// MailInfo

// optional int64 var_id = 1;
inline bool MailInfo::_internal_has_var_id() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool MailInfo::has_var_id() const {
  return _internal_has_var_id();
}
inline void MailInfo::clear_var_id() {
  var_id_ = PROTOBUF_LONGLONG(0);
  _has_bits_[0] &= ~0x00000010u;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MailInfo::_internal_var_id() const {
  return var_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int64 MailInfo::var_id() const {
  // @@protoc_insertion_point(field_get:MailInfo.var_id)
  return _internal_var_id();
}
inline void MailInfo::_internal_set_var_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _has_bits_[0] |= 0x00000010u;
  var_id_ = value;
}
inline void MailInfo::set_var_id(::PROTOBUF_NAMESPACE_ID::int64 value) {
  _internal_set_var_id(value);
  // @@protoc_insertion_point(field_set:MailInfo.var_id)
}

// optional string var_title = 2;
inline bool MailInfo::_internal_has_var_title() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool MailInfo::has_var_title() const {
  return _internal_has_var_title();
}
inline void MailInfo::clear_var_title() {
  var_title_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& MailInfo::var_title() const {
  // @@protoc_insertion_point(field_get:MailInfo.var_title)
  return _internal_var_title();
}
inline void MailInfo::set_var_title(const std::string& value) {
  _internal_set_var_title(value);
  // @@protoc_insertion_point(field_set:MailInfo.var_title)
}
inline std::string* MailInfo::mutable_var_title() {
  // @@protoc_insertion_point(field_mutable:MailInfo.var_title)
  return _internal_mutable_var_title();
}
inline const std::string& MailInfo::_internal_var_title() const {
  return var_title_.GetNoArena();
}
inline void MailInfo::_internal_set_var_title(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  var_title_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void MailInfo::set_var_title(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  var_title_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MailInfo.var_title)
}
inline void MailInfo::set_var_title(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  var_title_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MailInfo.var_title)
}
inline void MailInfo::set_var_title(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  var_title_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MailInfo.var_title)
}
inline std::string* MailInfo::_internal_mutable_var_title() {
  _has_bits_[0] |= 0x00000001u;
  return var_title_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* MailInfo::release_var_title() {
  // @@protoc_insertion_point(field_release:MailInfo.var_title)
  if (!_internal_has_var_title()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return var_title_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void MailInfo::set_allocated_var_title(std::string* var_title) {
  if (var_title != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  var_title_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), var_title);
  // @@protoc_insertion_point(field_set_allocated:MailInfo.var_title)
}

// optional string var_content = 3;
inline bool MailInfo::_internal_has_var_content() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool MailInfo::has_var_content() const {
  return _internal_has_var_content();
}
inline void MailInfo::clear_var_content() {
  var_content_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& MailInfo::var_content() const {
  // @@protoc_insertion_point(field_get:MailInfo.var_content)
  return _internal_var_content();
}
inline void MailInfo::set_var_content(const std::string& value) {
  _internal_set_var_content(value);
  // @@protoc_insertion_point(field_set:MailInfo.var_content)
}
inline std::string* MailInfo::mutable_var_content() {
  // @@protoc_insertion_point(field_mutable:MailInfo.var_content)
  return _internal_mutable_var_content();
}
inline const std::string& MailInfo::_internal_var_content() const {
  return var_content_.GetNoArena();
}
inline void MailInfo::_internal_set_var_content(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  var_content_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void MailInfo::set_var_content(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  var_content_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MailInfo.var_content)
}
inline void MailInfo::set_var_content(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  var_content_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MailInfo.var_content)
}
inline void MailInfo::set_var_content(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000002u;
  var_content_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MailInfo.var_content)
}
inline std::string* MailInfo::_internal_mutable_var_content() {
  _has_bits_[0] |= 0x00000002u;
  return var_content_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* MailInfo::release_var_content() {
  // @@protoc_insertion_point(field_release:MailInfo.var_content)
  if (!_internal_has_var_content()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return var_content_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void MailInfo::set_allocated_var_content(std::string* var_content) {
  if (var_content != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  var_content_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), var_content);
  // @@protoc_insertion_point(field_set_allocated:MailInfo.var_content)
}

// optional string var_date = 4;
inline bool MailInfo::_internal_has_var_date() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool MailInfo::has_var_date() const {
  return _internal_has_var_date();
}
inline void MailInfo::clear_var_date() {
  var_date_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& MailInfo::var_date() const {
  // @@protoc_insertion_point(field_get:MailInfo.var_date)
  return _internal_var_date();
}
inline void MailInfo::set_var_date(const std::string& value) {
  _internal_set_var_date(value);
  // @@protoc_insertion_point(field_set:MailInfo.var_date)
}
inline std::string* MailInfo::mutable_var_date() {
  // @@protoc_insertion_point(field_mutable:MailInfo.var_date)
  return _internal_mutable_var_date();
}
inline const std::string& MailInfo::_internal_var_date() const {
  return var_date_.GetNoArena();
}
inline void MailInfo::_internal_set_var_date(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  var_date_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void MailInfo::set_var_date(std::string&& value) {
  _has_bits_[0] |= 0x00000004u;
  var_date_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MailInfo.var_date)
}
inline void MailInfo::set_var_date(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000004u;
  var_date_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MailInfo.var_date)
}
inline void MailInfo::set_var_date(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000004u;
  var_date_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MailInfo.var_date)
}
inline std::string* MailInfo::_internal_mutable_var_date() {
  _has_bits_[0] |= 0x00000004u;
  return var_date_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* MailInfo::release_var_date() {
  // @@protoc_insertion_point(field_release:MailInfo.var_date)
  if (!_internal_has_var_date()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  return var_date_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void MailInfo::set_allocated_var_date(std::string* var_date) {
  if (var_date != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  var_date_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), var_date);
  // @@protoc_insertion_point(field_set_allocated:MailInfo.var_date)
}

// optional string var_name = 5;
inline bool MailInfo::_internal_has_var_name() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool MailInfo::has_var_name() const {
  return _internal_has_var_name();
}
inline void MailInfo::clear_var_name() {
  var_name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000008u;
}
inline const std::string& MailInfo::var_name() const {
  // @@protoc_insertion_point(field_get:MailInfo.var_name)
  return _internal_var_name();
}
inline void MailInfo::set_var_name(const std::string& value) {
  _internal_set_var_name(value);
  // @@protoc_insertion_point(field_set:MailInfo.var_name)
}
inline std::string* MailInfo::mutable_var_name() {
  // @@protoc_insertion_point(field_mutable:MailInfo.var_name)
  return _internal_mutable_var_name();
}
inline const std::string& MailInfo::_internal_var_name() const {
  return var_name_.GetNoArena();
}
inline void MailInfo::_internal_set_var_name(const std::string& value) {
  _has_bits_[0] |= 0x00000008u;
  var_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void MailInfo::set_var_name(std::string&& value) {
  _has_bits_[0] |= 0x00000008u;
  var_name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:MailInfo.var_name)
}
inline void MailInfo::set_var_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000008u;
  var_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MailInfo.var_name)
}
inline void MailInfo::set_var_name(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000008u;
  var_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MailInfo.var_name)
}
inline std::string* MailInfo::_internal_mutable_var_name() {
  _has_bits_[0] |= 0x00000008u;
  return var_name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* MailInfo::release_var_name() {
  // @@protoc_insertion_point(field_release:MailInfo.var_name)
  if (!_internal_has_var_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000008u;
  return var_name_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void MailInfo::set_allocated_var_name(std::string* var_name) {
  if (var_name != nullptr) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  var_name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), var_name);
  // @@protoc_insertion_point(field_set_allocated:MailInfo.var_name)
}

// -------------------------------------------------------------------

// RoomMessage

// optional string var_name = 1;
inline bool RoomMessage::_internal_has_var_name() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool RoomMessage::has_var_name() const {
  return _internal_has_var_name();
}
inline void RoomMessage::clear_var_name() {
  var_name_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& RoomMessage::var_name() const {
  // @@protoc_insertion_point(field_get:RoomMessage.var_name)
  return _internal_var_name();
}
inline void RoomMessage::set_var_name(const std::string& value) {
  _internal_set_var_name(value);
  // @@protoc_insertion_point(field_set:RoomMessage.var_name)
}
inline std::string* RoomMessage::mutable_var_name() {
  // @@protoc_insertion_point(field_mutable:RoomMessage.var_name)
  return _internal_mutable_var_name();
}
inline const std::string& RoomMessage::_internal_var_name() const {
  return var_name_.GetNoArena();
}
inline void RoomMessage::_internal_set_var_name(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  var_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void RoomMessage::set_var_name(std::string&& value) {
  _has_bits_[0] |= 0x00000001u;
  var_name_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:RoomMessage.var_name)
}
inline void RoomMessage::set_var_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000001u;
  var_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:RoomMessage.var_name)
}
inline void RoomMessage::set_var_name(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000001u;
  var_name_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:RoomMessage.var_name)
}
inline std::string* RoomMessage::_internal_mutable_var_name() {
  _has_bits_[0] |= 0x00000001u;
  return var_name_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* RoomMessage::release_var_name() {
  // @@protoc_insertion_point(field_release:RoomMessage.var_name)
  if (!_internal_has_var_name()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  return var_name_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void RoomMessage::set_allocated_var_name(std::string* var_name) {
  if (var_name != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  var_name_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), var_name);
  // @@protoc_insertion_point(field_set_allocated:RoomMessage.var_name)
}

// optional string var_message = 2;
inline bool RoomMessage::_internal_has_var_message() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool RoomMessage::has_var_message() const {
  return _internal_has_var_message();
}
inline void RoomMessage::clear_var_message() {
  var_message_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& RoomMessage::var_message() const {
  // @@protoc_insertion_point(field_get:RoomMessage.var_message)
  return _internal_var_message();
}
inline void RoomMessage::set_var_message(const std::string& value) {
  _internal_set_var_message(value);
  // @@protoc_insertion_point(field_set:RoomMessage.var_message)
}
inline std::string* RoomMessage::mutable_var_message() {
  // @@protoc_insertion_point(field_mutable:RoomMessage.var_message)
  return _internal_mutable_var_message();
}
inline const std::string& RoomMessage::_internal_var_message() const {
  return var_message_.GetNoArena();
}
inline void RoomMessage::_internal_set_var_message(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  var_message_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void RoomMessage::set_var_message(std::string&& value) {
  _has_bits_[0] |= 0x00000002u;
  var_message_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:RoomMessage.var_message)
}
inline void RoomMessage::set_var_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000002u;
  var_message_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:RoomMessage.var_message)
}
inline void RoomMessage::set_var_message(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000002u;
  var_message_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:RoomMessage.var_message)
}
inline std::string* RoomMessage::_internal_mutable_var_message() {
  _has_bits_[0] |= 0x00000002u;
  return var_message_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* RoomMessage::release_var_message() {
  // @@protoc_insertion_point(field_release:RoomMessage.var_message)
  if (!_internal_has_var_message()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  return var_message_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void RoomMessage::set_allocated_var_message(std::string* var_message) {
  if (var_message != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  var_message_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), var_message);
  // @@protoc_insertion_point(field_set_allocated:RoomMessage.var_message)
}

// optional int32 var_message_int = 3;
inline bool RoomMessage::_internal_has_var_message_int() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool RoomMessage::has_var_message_int() const {
  return _internal_has_var_message_int();
}
inline void RoomMessage::clear_var_message_int() {
  var_message_int_ = 0;
  _has_bits_[0] &= ~0x00000008u;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RoomMessage::_internal_var_message_int() const {
  return var_message_int_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RoomMessage::var_message_int() const {
  // @@protoc_insertion_point(field_get:RoomMessage.var_message_int)
  return _internal_var_message_int();
}
inline void RoomMessage::_internal_set_var_message_int(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _has_bits_[0] |= 0x00000008u;
  var_message_int_ = value;
}
inline void RoomMessage::set_var_message_int(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_var_message_int(value);
  // @@protoc_insertion_point(field_set:RoomMessage.var_message_int)
}

// optional string var_time = 4;
inline bool RoomMessage::_internal_has_var_time() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool RoomMessage::has_var_time() const {
  return _internal_has_var_time();
}
inline void RoomMessage::clear_var_time() {
  var_time_.ClearToEmptyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& RoomMessage::var_time() const {
  // @@protoc_insertion_point(field_get:RoomMessage.var_time)
  return _internal_var_time();
}
inline void RoomMessage::set_var_time(const std::string& value) {
  _internal_set_var_time(value);
  // @@protoc_insertion_point(field_set:RoomMessage.var_time)
}
inline std::string* RoomMessage::mutable_var_time() {
  // @@protoc_insertion_point(field_mutable:RoomMessage.var_time)
  return _internal_mutable_var_time();
}
inline const std::string& RoomMessage::_internal_var_time() const {
  return var_time_.GetNoArena();
}
inline void RoomMessage::_internal_set_var_time(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  var_time_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value);
}
inline void RoomMessage::set_var_time(std::string&& value) {
  _has_bits_[0] |= 0x00000004u;
  var_time_.SetNoArena(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:RoomMessage.var_time)
}
inline void RoomMessage::set_var_time(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  _has_bits_[0] |= 0x00000004u;
  var_time_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:RoomMessage.var_time)
}
inline void RoomMessage::set_var_time(const char* value, size_t size) {
  _has_bits_[0] |= 0x00000004u;
  var_time_.SetNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:RoomMessage.var_time)
}
inline std::string* RoomMessage::_internal_mutable_var_time() {
  _has_bits_[0] |= 0x00000004u;
  return var_time_.MutableNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline std::string* RoomMessage::release_var_time() {
  // @@protoc_insertion_point(field_release:RoomMessage.var_time)
  if (!_internal_has_var_time()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  return var_time_.ReleaseNonDefaultNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}
inline void RoomMessage::set_allocated_var_time(std::string* var_time) {
  if (var_time != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  var_time_.SetAllocatedNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), var_time);
  // @@protoc_insertion_point(field_set_allocated:RoomMessage.var_time)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Structure_2eproto
